version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install --upgrade awscli
      - command -v zip >/dev/null 2>&1 || yum install -y zip

  build:
    commands:
      - set -e
      - ARTIFACTS_DIR=${ARTIFACTS_DIR:-artifacts}
      - mkdir -p "$ARTIFACTS_DIR"

      - echo "Zipping index-photos lambda..."
      - (cd lambdas/index-photos && zip -r "../../$ARTIFACTS_DIR/index-photos.zip" .)

      - echo "Zipping search-photos lambda..."
      - (cd lambdas/search-photos && zip -r "../../$ARTIFACTS_DIR/search-photos.zip" .)

artifacts:
  base-directory: artifacts
  files:
    - index-photos.zip
    - search-photos.zip
