version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade awscli

  build:
    commands:
      - echo "Deploying frontend to S3..."
      - aws s3 sync frontend/ s3://cc-hw3-b1-frontend/ --delete --region us-east-1

artifacts:
  files: []
