version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install --upgrade awscli

  build:
    commands:
      - echo "Zipping index-photos lambda..."
      - cd lambdas/index-photos
      - zip -r /tmp/index-photos.zip .
      - cd ../../

      - echo "Zipping search-photos lambda..."
      - cd lambdas/search-photos
      - zip -r /tmp/search-photos.zip .
      - cd ../../

  post_build:
    commands:
      - echo "Updating Lambda functions..."
      - aws lambda update-function-code \
          --function-name YOUR_INDEX_LAMBDA_NAME \
          --zip-file fileb:///tmp/index-photos.zip \
          --region us-east-1

      - aws lambda update-function-code \
          --function-name YOUR_SEARCH_LAMBDA_NAME \
          --zip-file fileb:///tmp/search-photos.zip \
          --region us-east-1

artifacts:
  files: []
